spring:
  application:
    name: "authorization-server"
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
server:
  servlet:
    context-path: "/auth"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
